[[LLVMCompilerRT]]
arch = "aarch64"
git-tree-sha1 = "d793abb70ccb4048b2c4c0480b3e5b339e478cee"
os = "macos"

    [[LLVMCompilerRT.download]]
    sha256 = "be4a0432637d8d5f5186dd7a18c052d45182aceb1fbaad1d95b7e90ee20a9c83"
    url = "https://github.com/JuliaBinaryWrappers/LLVMCompilerRT_jll.jl/releases/download/LLVMCompilerRT-v17.0.6+0/LLVMCompilerRT.v17.0.6.aarch64-apple-darwin.tar.gz"
[[LLVMCompilerRT]]
arch = "aarch64"
git-tree-sha1 = "d8b892c7e499967271c66631f21c7a7bed4a0060"
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "250df83618e09e44bffe092e272cbbce9b669ddbd28f67d735e6de206352a718"
    url = "https://github.com/JuliaBinaryWrappers/LLVMCompilerRT_jll.jl/releases/download/LLVMCompilerRT-v17.0.6+0/LLVMCompilerRT.v17.0.6.aarch64-linux-gnu.tar.gz"
[[LLVMCompilerRT]]
arch = "aarch64"
git-tree-sha1 = "d8b892c7e499967271c66631f21c7a7bed4a0060"
libc = "musl"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "250df83618e09e44bffe092e272cbbce9b669ddbd28f67d735e6de206352a718"
    url = "https://github.com/JuliaBinaryWrappers/LLVMCompilerRT_jll.jl/releases/download/LLVMCompilerRT-v17.0.6+0/LLVMCompilerRT.v17.0.6.aarch64-linux-musl.tar.gz"
[[LLVMCompilerRT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d8b892c7e499967271c66631f21c7a7bed4a0060"
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "250df83618e09e44bffe092e272cbbce9b669ddbd28f67d735e6de206352a718"
    url = "https://github.com/JuliaBinaryWrappers/LLVMCompilerRT_jll.jl/releases/download/LLVMCompilerRT-v17.0.6+0/LLVMCompilerRT.v17.0.6.armv6l-linux-gnueabihf.tar.gz"
[[LLVMCompilerRT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d8b892c7e499967271c66631f21c7a7bed4a0060"
libc = "musl"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "250df83618e09e44bffe092e272cbbce9b669ddbd28f67d735e6de206352a718"
    url = "https://github.com/JuliaBinaryWrappers/LLVMCompilerRT_jll.jl/releases/download/LLVMCompilerRT-v17.0.6+0/LLVMCompilerRT.v17.0.6.armv6l-linux-musleabihf.tar.gz"
[[LLVMCompilerRT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d8b892c7e499967271c66631f21c7a7bed4a0060"
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "250df83618e09e44bffe092e272cbbce9b669ddbd28f67d735e6de206352a718"
    url = "https://github.com/JuliaBinaryWrappers/LLVMCompilerRT_jll.jl/releases/download/LLVMCompilerRT-v17.0.6+0/LLVMCompilerRT.v17.0.6.armv7l-linux-gnueabihf.tar.gz"
[[LLVMCompilerRT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d8b892c7e499967271c66631f21c7a7bed4a0060"
libc = "musl"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "250df83618e09e44bffe092e272cbbce9b669ddbd28f67d735e6de206352a718"
    url = "https://github.com/JuliaBinaryWrappers/LLVMCompilerRT_jll.jl/releases/download/LLVMCompilerRT-v17.0.6+0/LLVMCompilerRT.v17.0.6.armv7l-linux-musleabihf.tar.gz"
[[LLVMCompilerRT]]
arch = "i686"
git-tree-sha1 = "712189b811f5210aa49273d200f1558e48eac244"
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "1877a128621443ad4361a2785a8b493602028cd882ac6999b7e987915a1517e1"
    url = "https://github.com/JuliaBinaryWrappers/LLVMCompilerRT_jll.jl/releases/download/LLVMCompilerRT-v17.0.6+0/LLVMCompilerRT.v17.0.6.i686-linux-gnu.tar.gz"
[[LLVMCompilerRT]]
arch = "i686"
git-tree-sha1 = "30a85ce12d255bc4c6f2c9aa77fe957c16dedb15"
os = "windows"

    [[LLVMCompilerRT.download]]
    sha256 = "ba83af08f9003ea039fcae0964f59f0a78eb33284420c0534e4aa902459a6c62"
    url = "https://github.com/JuliaBinaryWrappers/LLVMCompilerRT_jll.jl/releases/download/LLVMCompilerRT-v17.0.6+0/LLVMCompilerRT.v17.0.6.i686-w64-mingw32.tar.gz"
[[LLVMCompilerRT]]
arch = "x86_64"
git-tree-sha1 = "5c6b904c05a4cea31c87cb1d7b9f95903fbb1805"
os = "macos"

    [[LLVMCompilerRT.download]]
    sha256 = "acf93a2a166551eff5db7b18dc7144446a49f0af0d11e45be7033303ca37a4f6"
    url = "https://github.com/JuliaBinaryWrappers/LLVMCompilerRT_jll.jl/releases/download/LLVMCompilerRT-v17.0.6+0/LLVMCompilerRT.v17.0.6.x86_64-apple-darwin.tar.gz"
[[LLVMCompilerRT]]
arch = "x86_64"
git-tree-sha1 = "5c7d4222646e2a03adf3b79dc06f3f5b18c669d3"
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "81a601d4fa01887f300f28407b4ef6779014db27f976d93c09e4d3ee46690c8e"
    url = "https://github.com/JuliaBinaryWrappers/LLVMCompilerRT_jll.jl/releases/download/LLVMCompilerRT-v17.0.6+0/LLVMCompilerRT.v17.0.6.x86_64-linux-gnu.tar.gz"
[[LLVMCompilerRT]]
arch = "x86_64"
git-tree-sha1 = "87a836790da5a608210cfeaded9b23802dd804c6"
os = "freebsd"

    [[LLVMCompilerRT.download]]
    sha256 = "8d972ba6846b2ef65eefccb2e80b9d74f536688b4d5569ed34bf7744fd41dae2"
    url = "https://github.com/JuliaBinaryWrappers/LLVMCompilerRT_jll.jl/releases/download/LLVMCompilerRT-v17.0.6+0/LLVMCompilerRT.v17.0.6.x86_64-unknown-freebsd.tar.gz"
[[LLVMCompilerRT]]
arch = "x86_64"
git-tree-sha1 = "90de9d9999c384867f12930cd4e13bc3207a1e7b"
os = "windows"

    [[LLVMCompilerRT.download]]
    sha256 = "46ebec82816806ab91a7a45079315771af63ef00a533289dcc9f2e558aa12080"
    url = "https://github.com/JuliaBinaryWrappers/LLVMCompilerRT_jll.jl/releases/download/LLVMCompilerRT-v17.0.6+0/LLVMCompilerRT.v17.0.6.x86_64-w64-mingw32.tar.gz"
