[[LLVMCompilerRT]]
arch = "aarch64"
git-tree-sha1 = "fed716f91eac1131e43bd80273903085372d00d1"
os = "macos"

    [[LLVMCompilerRT.download]]
    sha256 = "e39dea6fb44f773b03d20a5ad13edf27855314be62600419f51da5cee37dcfa4"
    url = "https://github.com/JuliaBinaryWrappers/LLVMCompilerRT_jll.jl/releases/download/LLVMCompilerRT-v13.0.1+0/LLVMCompilerRT.v13.0.1.aarch64-apple-darwin.tar.gz"
[[LLVMCompilerRT]]
arch = "aarch64"
git-tree-sha1 = "c1979bc8a2475f55fe95913cb1aa7a13db213180"
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "83ae33e25bf19da6af5b2c476a0616c49246edec81fb05942bf83a63dc41bcd8"
    url = "https://github.com/JuliaBinaryWrappers/LLVMCompilerRT_jll.jl/releases/download/LLVMCompilerRT-v13.0.1+0/LLVMCompilerRT.v13.0.1.aarch64-linux-gnu.tar.gz"
[[LLVMCompilerRT]]
arch = "aarch64"
git-tree-sha1 = "b8942c582089d1aea961c415e17caf93698a4c70"
libc = "musl"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "42c08233f1266e5b1eae2fd1b024fd96e86210728b58c9760393b706fdee81fb"
    url = "https://github.com/JuliaBinaryWrappers/LLVMCompilerRT_jll.jl/releases/download/LLVMCompilerRT-v13.0.1+0/LLVMCompilerRT.v13.0.1.aarch64-linux-musl.tar.gz"
[[LLVMCompilerRT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a244d8ec6ba78544e67460582b288bc5870983ef"
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "9cc0a19f849c17d429f9ec3aefdcdabe1f6e95c9fb9ffe7b7be0d1f7c586de0f"
    url = "https://github.com/JuliaBinaryWrappers/LLVMCompilerRT_jll.jl/releases/download/LLVMCompilerRT-v13.0.1+0/LLVMCompilerRT.v13.0.1.armv6l-linux-gnueabihf.tar.gz"
[[LLVMCompilerRT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7746f6f6a93be1d640ee2840903ba81306692583"
libc = "musl"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "6be59617715dc63395ccf9edd6d70276c67bc34b0ac0b3b4406ae1ac54e071ab"
    url = "https://github.com/JuliaBinaryWrappers/LLVMCompilerRT_jll.jl/releases/download/LLVMCompilerRT-v13.0.1+0/LLVMCompilerRT.v13.0.1.armv6l-linux-musleabihf.tar.gz"
[[LLVMCompilerRT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "64798a4ebc7868993ab20b9610c09d23b7c1a307"
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "bd01eb8f8dbec56455d9979efc6ff3c1b5097e495f1d74004062753cce93b10e"
    url = "https://github.com/JuliaBinaryWrappers/LLVMCompilerRT_jll.jl/releases/download/LLVMCompilerRT-v13.0.1+0/LLVMCompilerRT.v13.0.1.armv7l-linux-gnueabihf.tar.gz"
[[LLVMCompilerRT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f3552b5a04fafa04c94ba7b988a9ef8e2e41448a"
libc = "musl"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "7a826ed5db9dc03932944b1f72f98f106eb0aa9c3004c99a9b183f41f331c516"
    url = "https://github.com/JuliaBinaryWrappers/LLVMCompilerRT_jll.jl/releases/download/LLVMCompilerRT-v13.0.1+0/LLVMCompilerRT.v13.0.1.armv7l-linux-musleabihf.tar.gz"
[[LLVMCompilerRT]]
arch = "i686"
git-tree-sha1 = "f5f4b69b17d4dc973130338725a2bf67ed535dad"
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "4425f5c138a9e8a09007882109a65ceeb813ea438b7d7f057fc7e2e3e1dee958"
    url = "https://github.com/JuliaBinaryWrappers/LLVMCompilerRT_jll.jl/releases/download/LLVMCompilerRT-v13.0.1+0/LLVMCompilerRT.v13.0.1.i686-linux-gnu.tar.gz"
[[LLVMCompilerRT]]
arch = "i686"
git-tree-sha1 = "9e599a34b7001181e18cd28d01e1561d27e345e9"
os = "windows"

    [[LLVMCompilerRT.download]]
    sha256 = "dc3b327d02a2981e04ec67dd684ce3438e7a0058585033c8f09a73127999c45d"
    url = "https://github.com/JuliaBinaryWrappers/LLVMCompilerRT_jll.jl/releases/download/LLVMCompilerRT-v13.0.1+0/LLVMCompilerRT.v13.0.1.i686-w64-mingw32.tar.gz"
[[LLVMCompilerRT]]
arch = "x86_64"
git-tree-sha1 = "d5384754e7099b180e9e89d82d8fb9330b60c9d7"
os = "macos"

    [[LLVMCompilerRT.download]]
    sha256 = "ba6ad78d632d161a139dc9002218dcc7e1fe85331735e10de78cef2a1c2815e0"
    url = "https://github.com/JuliaBinaryWrappers/LLVMCompilerRT_jll.jl/releases/download/LLVMCompilerRT-v13.0.1+0/LLVMCompilerRT.v13.0.1.x86_64-apple-darwin.tar.gz"
[[LLVMCompilerRT]]
arch = "x86_64"
git-tree-sha1 = "b5c372dac846b26a2c396c19ca3441188d4ea67c"
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "73d3047b0e64827391de2c6a945166f1af098c61e93fa161b857bdf3f4005f9e"
    url = "https://github.com/JuliaBinaryWrappers/LLVMCompilerRT_jll.jl/releases/download/LLVMCompilerRT-v13.0.1+0/LLVMCompilerRT.v13.0.1.x86_64-linux-gnu.tar.gz"
[[LLVMCompilerRT]]
arch = "x86_64"
git-tree-sha1 = "72c63e316983c206c2fd164414ac5e411890b36d"
os = "freebsd"

    [[LLVMCompilerRT.download]]
    sha256 = "32dfc5621baf68bfa8a29e1627f80e6f68056de0b7f5eb504f82c8c7a68c6d01"
    url = "https://github.com/JuliaBinaryWrappers/LLVMCompilerRT_jll.jl/releases/download/LLVMCompilerRT-v13.0.1+0/LLVMCompilerRT.v13.0.1.x86_64-unknown-freebsd.tar.gz"
[[LLVMCompilerRT]]
arch = "x86_64"
git-tree-sha1 = "0e384bc34337307aea3e1330b355ac41a8ba45eb"
os = "windows"

    [[LLVMCompilerRT.download]]
    sha256 = "d2bf5ec3da7640f6164350f14ebf05a10e6079dd14a1108a401233964ec842a0"
    url = "https://github.com/JuliaBinaryWrappers/LLVMCompilerRT_jll.jl/releases/download/LLVMCompilerRT-v13.0.1+0/LLVMCompilerRT.v13.0.1.x86_64-w64-mingw32.tar.gz"
