[[LLVMCompilerRT]]
arch = "aarch64"
git-tree-sha1 = "8f0557644013a7c0c2c02332f8f74cfb7d76f05f"
os = "macos"

    [[LLVMCompilerRT.download]]
    sha256 = "f80bae21e211032f58aa824fec57bc44c59f752afd9231ef9076c199a7f28172"
    url = "https://github.com/JuliaBinaryWrappers/LLVMCompilerRT_jll.jl/releases/download/LLVMCompilerRT-v13.0.1+1/LLVMCompilerRT.v13.0.1.aarch64-apple-darwin.tar.gz"
[[LLVMCompilerRT]]
arch = "aarch64"
git-tree-sha1 = "e7793be90ee45efdec3a6c12b28f384beecfc612"
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "429b203dbcd4c4de3b635fc42c300dab5bc177b819c3061651ee2aed7ccfb9c8"
    url = "https://github.com/JuliaBinaryWrappers/LLVMCompilerRT_jll.jl/releases/download/LLVMCompilerRT-v13.0.1+1/LLVMCompilerRT.v13.0.1.aarch64-linux-gnu.tar.gz"
[[LLVMCompilerRT]]
arch = "aarch64"
git-tree-sha1 = "e7793be90ee45efdec3a6c12b28f384beecfc612"
libc = "musl"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "429b203dbcd4c4de3b635fc42c300dab5bc177b819c3061651ee2aed7ccfb9c8"
    url = "https://github.com/JuliaBinaryWrappers/LLVMCompilerRT_jll.jl/releases/download/LLVMCompilerRT-v13.0.1+1/LLVMCompilerRT.v13.0.1.aarch64-linux-musl.tar.gz"
[[LLVMCompilerRT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e7793be90ee45efdec3a6c12b28f384beecfc612"
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "429b203dbcd4c4de3b635fc42c300dab5bc177b819c3061651ee2aed7ccfb9c8"
    url = "https://github.com/JuliaBinaryWrappers/LLVMCompilerRT_jll.jl/releases/download/LLVMCompilerRT-v13.0.1+1/LLVMCompilerRT.v13.0.1.armv6l-linux-gnueabihf.tar.gz"
[[LLVMCompilerRT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e7793be90ee45efdec3a6c12b28f384beecfc612"
libc = "musl"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "429b203dbcd4c4de3b635fc42c300dab5bc177b819c3061651ee2aed7ccfb9c8"
    url = "https://github.com/JuliaBinaryWrappers/LLVMCompilerRT_jll.jl/releases/download/LLVMCompilerRT-v13.0.1+1/LLVMCompilerRT.v13.0.1.armv6l-linux-musleabihf.tar.gz"
[[LLVMCompilerRT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e7793be90ee45efdec3a6c12b28f384beecfc612"
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "429b203dbcd4c4de3b635fc42c300dab5bc177b819c3061651ee2aed7ccfb9c8"
    url = "https://github.com/JuliaBinaryWrappers/LLVMCompilerRT_jll.jl/releases/download/LLVMCompilerRT-v13.0.1+1/LLVMCompilerRT.v13.0.1.armv7l-linux-gnueabihf.tar.gz"
[[LLVMCompilerRT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e7793be90ee45efdec3a6c12b28f384beecfc612"
libc = "musl"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "429b203dbcd4c4de3b635fc42c300dab5bc177b819c3061651ee2aed7ccfb9c8"
    url = "https://github.com/JuliaBinaryWrappers/LLVMCompilerRT_jll.jl/releases/download/LLVMCompilerRT-v13.0.1+1/LLVMCompilerRT.v13.0.1.armv7l-linux-musleabihf.tar.gz"
[[LLVMCompilerRT]]
arch = "i686"
git-tree-sha1 = "57162bb765330c4ee4c0a37b9fbc63e270fed0b2"
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "15ef131bdabfb2f7929363c4bf488ab3d420118db85693e45fb8b6cc81f091c1"
    url = "https://github.com/JuliaBinaryWrappers/LLVMCompilerRT_jll.jl/releases/download/LLVMCompilerRT-v13.0.1+1/LLVMCompilerRT.v13.0.1.i686-linux-gnu.tar.gz"
[[LLVMCompilerRT]]
arch = "i686"
git-tree-sha1 = "e8afe12d9d85502866276416632c870a7caf0041"
os = "windows"

    [[LLVMCompilerRT.download]]
    sha256 = "a47de7ecebca7791c08a359f812fc216754826ee713b16ab811f5320eb952ad0"
    url = "https://github.com/JuliaBinaryWrappers/LLVMCompilerRT_jll.jl/releases/download/LLVMCompilerRT-v13.0.1+1/LLVMCompilerRT.v13.0.1.i686-w64-mingw32.tar.gz"
[[LLVMCompilerRT]]
arch = "x86_64"
git-tree-sha1 = "ba7004950d8fe41752b25988edfa6d79994b27ca"
os = "macos"

    [[LLVMCompilerRT.download]]
    sha256 = "117fce655cbc96110ebcd97cbe274a224ce823c8ac6be48e04db77b8e2c6fbdf"
    url = "https://github.com/JuliaBinaryWrappers/LLVMCompilerRT_jll.jl/releases/download/LLVMCompilerRT-v13.0.1+1/LLVMCompilerRT.v13.0.1.x86_64-apple-darwin.tar.gz"
[[LLVMCompilerRT]]
arch = "x86_64"
git-tree-sha1 = "6678d04a6dfb7409694b9fd8f7743326a654f66e"
libc = "glibc"
os = "linux"

    [[LLVMCompilerRT.download]]
    sha256 = "789c93e943e2ee369e065314bd9b7eed8d285ac1ed70753ba2beb2989c915cd1"
    url = "https://github.com/JuliaBinaryWrappers/LLVMCompilerRT_jll.jl/releases/download/LLVMCompilerRT-v13.0.1+1/LLVMCompilerRT.v13.0.1.x86_64-linux-gnu.tar.gz"
[[LLVMCompilerRT]]
arch = "x86_64"
git-tree-sha1 = "8789c47031827ec72c63a24a4a2405f84fff0611"
os = "freebsd"

    [[LLVMCompilerRT.download]]
    sha256 = "989affb2f84d8978ce13d77528e694225223e75805899f196100dc78b6adab54"
    url = "https://github.com/JuliaBinaryWrappers/LLVMCompilerRT_jll.jl/releases/download/LLVMCompilerRT-v13.0.1+1/LLVMCompilerRT.v13.0.1.x86_64-unknown-freebsd.tar.gz"
[[LLVMCompilerRT]]
arch = "x86_64"
git-tree-sha1 = "aa9b774c963fabeed52f9999118039cb850ed5bc"
os = "windows"

    [[LLVMCompilerRT.download]]
    sha256 = "5806113de221c3f6a1a981eea427323b3574cfc2000d239762df12585fb70de9"
    url = "https://github.com/JuliaBinaryWrappers/LLVMCompilerRT_jll.jl/releases/download/LLVMCompilerRT-v13.0.1+1/LLVMCompilerRT.v13.0.1.x86_64-w64-mingw32.tar.gz"
