[[LLVMCompilerRT]]
arch = "aarch64"
git-tree-sha1 = "c988fa9483e74bdefaed12cfc5b20eaea54fb45f"
os = "macos"

    [[LLVMCompilerRT.download]]
    sha256 = "c309c89c199a5e2a11ad70ae38a6bc4ea2635e63e78b42de0f7329ef3a923c29"
    url = "https://github.com/JuliaBinaryWrappers/LLVMCompilerRT_jll.jl/releases/download/LLVMCompilerRT-v16.0.6+0/LLVMCompilerRT.v16.0.6.aarch64-apple-darwin.tar.gz"
